### PR TITLE
Hugo/performance

### PR DESCRIPTION
**Pull request by hugohadfield**
Adds numba as a dependency
Speeds up multiplication code via jitting and sparseness
Speeds up high dimensional algebra generation by jitting

### CODE REVIEW

**Comment by arsenovic** [comment]
i measure a speedup of 20s->5s on Cl(8)! awesome. 

so this looks like you have removed  methods of layout used in `__init__`,  jitted them,  which is fine with me. you might add some comments to explain this in the code. 

i use the docs as a test, which is really bad,  but it found the following. 

* bug:  the `comp_func` fails due to array broadcasting. i might have broke this when resolving https://github.com/pygae/clifford/issues/9, with https://github.com/arsenovic/clifford/commit/deb9648401f07ca6c5f22745d2055eb456095dca. you can test with `Cl(2)==Cl(3)` 

* you should also add the new numba dep to `readthedocs-environement.yml` for the docs

**Comment by hugohadfield** [comment]
@arsenovic not sure how I can replicate this comp_func error, Cl(2)==Cl(3) returns False as expected, what behaviour were you seeing?

**Comment by arsenovic** [comment]
i get this . 
```
>>>from clifford import Cl
>>>Cl(2)==Cl(3)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-a887d047d2cf> in <module>()
      1 from clifford import Cl
----> 2 Cl(2)==Cl(3)

/home/alex/code/clifford/clifford/__init__.py in __eq__(self, other)
    416 
    417     def __eq__(self,other):
--> 418         return not self.__ne__(other)
    419 
    420     def __ne__(self,other):

/home/alex/code/clifford/clifford/__init__.py in __ne__(self, other)
    419 
    420     def __ne__(self,other):
--> 421         return self.comp_func(other.sig)
    422 
    423     def _genEvenOdd(self):

ValueError: unable to broadcast argument 1 to output array
File "/home/alex/code/clifford/clifford/__init__.py", line 247
```

**Comment by moble** [comment]
I get the same as Alex, unless I comment out the `njit` decorator — which makes me worry that the code itself is kind of wrong.  The signatures being compared here are numpy arrays `[1,1]` and `[1,1,1]`.  If I just compare those directly, I get a `DeprecationWarning`:

```python
>>> import numpy as np
>>> a = np.array([1,1])
>>> b = np.array([1,1,1])
>>> a != b
DeprecationWarning: elementwise != comparison failed; this will raise an error in the future.
```
I guess the reason is that they're different lengths, and numpy is trying to compare each element.  The usual way to do this comparison would be with `np.array_equal`, which might be faster than the jitted code anyway.  That might be worth a try.

**Comment by hugohadfield** [comment]
@moble I wasn't aware numpy had that function! @arsenovic this should now hopefully be fixed, shall I merge to master?

**Comment by arsenovic** [comment]
works for me

**Pull request merged**
