### PR TITLE
Added minimal string parsing functionality

### PR DESCRIPTION
**Pull request by hugohadfield**
Adds the ability to do
```
mv_a == layout.parse_multivector(str(mv_a))
mv_a == cf.MultiVector(layout,string=str(mv_a))
```

### CODE REVIEW

**Comment by hugohadfield** [comment]
Related to https://github.com/pygae/clifford/issues/15

**Comment by arsenovic** [comment]
seems like accessing the MV.layout, and MV.value would be more direct like, `ugly()`?  however in the end, how its done  doesnt matter much.

**Comment by hugohadfield** [comment]
Definitely true that the current ugly() print + eval combo is more direct. Makes me feel fairly uncomfortable 'eval'ing user input though, thought it might be nice to have the capacity to do both

**Comment by arsenovic** [comment]
ok i see,  i agree with your string regex approx.

**Pull request merged**
