### PR TITLE
fix radius calculation

### LINKED ISSUE #184: cga.Round.radius is always 1
```python
>>> from clifford.cga import CGA
>>> cga = CGA(3)
>>> r = cga.round()
>>> r.radius
1
```

### PR DESCRIPTION
**Pull request by pavlo-melnyk**
Closes #184

### CODE REVIEW

**Comment by eric-wieser** [comment]
There are some tests in `test_cga.py` that are marked xfail because of this bug. Can you remove the marker?

**Comment by pavlo-melnyk** [comment]
Please clarify which marker

**Comment by eric-wieser** [comment]
Markers that mention the issue number you're fixing, like

https://github.com/pygae/clifford/blob/67ea8ae7b7b8004c4c8322949918d96b00e87fa7/clifford/test/test_cga.py#L84

**Comment by eric-wieser** [comment]
Thanks!

**Pull request merged**
