### PR TITLE
Hugo/sparse mult

### PR DESCRIPTION
**Pull request by hugohadfield**
Creates jitted sparse multiplication functions for mvs of specific grades
Now with added testing 
Note: Tests may take a while to run as it looks at all possible combinations of sparsity in grades of both objects

### CODE REVIEW

**Comment by arsenovic** [comment]
go right ahead. 

do you have an example of a use case for this, and the speedup it generates?

**Comment by hugohadfield** [comment]
OK cool, will make a gist to explain my reasoning

**Comment by hugohadfield** [comment]
OK, here is my arguments for this pull request:
https://gist.github.com/hugohadfield/f847a19aaf654f39b75f94da9b4e6fb2
Essentially it allows us to generate specialised functions for sparse multivectors in advance if we know their grade. In the case we do not specify the grades it does a runtime sparsity check as @moble suggested in https://github.com/pygae/clifford/issues/10. In the case of fully dense multivectors this will add overhead, in the more common case of sparse mvs it speeds up operations a lot for no extra effort.

**Comment by hugohadfield** [comment]
I added the ability to specify the filter mask directly so as to allow highly object specific optimisation eg. for when using the pseudoscalars from various spaces or other commonly used constants where we know the exact sparsity in advance at a finer resolution than simply the grade.

**Pull request merged**
