### PR TITLE
Use pyganja

### PR DESCRIPTION
**Pull request by eric-wieser**
Builds on top of #166, pushing now to test it works on readthedocs

### CODE REVIEW

**Comment by hugohadfield** [comment]
Looks cool, but the build is broken? https://external-builds.readthedocs.io/html/clifford/167/Example%201%20Interpolating%20Conformal%20Objects.html

**Comment by eric-wieser** [comment]
I think that's an upstream readthedocs bug. It works locally, with the pyganja changes.

**Comment by eric-wieser** [comment]
Going to just merge this, its doc-only, and the ReadTheDocs CI stuff isn't mature enough to work for these filenames. Let's just see if it works.

**Comment by eric-wieser** [comment]
Crap:

    ModuleNotFoundError: No module named 'pyganja'

**Pull request merged**
